name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    # Service containers to run with `test-job`
    services:
      # Label used to access the service container
      falkordb:
        # Docker Hub image
        image: falkordb/falkordb:edge
        # Map port 6379 on the Docker host to port 6379 on the FalkorDB container
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: |
          realversion="${GITHUB_REF/refs\/tags\//}"
          realversion="${realversion//v/}"
          echo "VERSION=$realversion" >> $GITHUB_OUTPUT

      - name: Set up JDK 8 for publishing to Maven Central
        uses: actions/setup-java@v5
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN

      - name: Update version in POM
        run: mvn versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }}

      - name: Import GPG key
        run: |
          echo "${{ secrets.OSSH_GPG_SECRET_KEY }}" | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Build and deploy to Maven Central
        run: |
          mvn --no-transfer-progress \
            --batch-mode \
            clean deploy
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSH_GPG_SECRET_KEY_PASSWORD }}
