name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    # Service containers to run with `test-job`
    services:
      # Label used to access the service container
      falkordb:
        # Docker Hub image
        image: falkordb/falkordb:edge
        # Map port 6379 on the Docker host to port 6379 on the FalkorDB container
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false

      - name: Get version from tag
        id: get_version
        run: |
          realversion="${GITHUB_REF/refs\/tags\//}"
          realversion="${realversion//v/}"
          echo "VERSION=$realversion" >> $GITHUB_OUTPUT

      - name: Set up JDK 21 for publishing to Maven Central
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN

      - name: Install just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4

      - name: Update version in POM
        run: just set-version "$VERSION"
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7
        with:
          gpg_private_key: ${{ secrets.OSSH_GPG_SECRET_KEY }}
          passphrase: ${{ secrets.OSSH_GPG_SECRET_KEY_PASSWORD }}

      - name: Build and deploy to Maven Central
        run: just deploy-release
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSH_GPG_SECRET_KEY_PASSWORD }}
